# Generated by Django 4.2 on 2023-06-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_rename_contactform_contactmodel'),
    ]

    operations = [
    ]
