# Generated by Django 4.2 on 2023-04-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_photo',
            new_name='product_foto',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='product_naam',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='product_prijs',
        ),
    ]
