# Generated by Django 4.2 on 2023-04-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_photo_product_product_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_foto',
            field=models.ImageField(blank=True, null=True, upload_to='product_foto/'),
        ),
    ]
