# Generated by Django 4.2 on 2023-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_product_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_naam',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_prijs',
            new_name='product_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_foto',
        ),
        migrations.AddField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo/'),
        ),
    ]
